version: '2'

services:
  fpm:
    image: 'koshpaevsv/php7.1'
    volumes:
      - './:/var/www'
    networks:
    - interior

  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    networks:
    - interior

networks:
  interior:
